### ISSUE TITLE
Docs for command line usage

### ISSUE THREAD

**Issue by wilg** [lemurheavy/coveralls-ruby#4]

**Comment by tansaku** [comment]
I really would like to display the statistics locally, but I get the following:

```
$ coveralls report
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/Users/tansaku/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/Users/tansaku/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by tansaku** [comment]
The above was odd, because I did have a Rakefile - I had been doing it with and without.  I think my problem was that I had it setup to run rubocop before rspec.  Rubocop was blocking and so I wasn't getting to the rspec run and the coveralls report - fixed that now.  Would still like to know if the detailed coverage data can be accessed locally or if that requires a separate simplecov run ...

**Comment by dentarg** [comment]
> Would still like to know if the detailed coverage data can be accessed locally or if that requires a separate simplecov run ...

Same here, `coveralls report` just seems to run my specs

**Comment by leusonmario** [comment]
Is there a tutorial, or something like this, showing how to use it? I thought the wiki could present more information about it.
